spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nextpress
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # later change to validate + Flyway migrations
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  session:
    store-type: redis
    timeout: 30m

redis:
  host: localhost
  port: 6379

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false   # set secure: true behind HTTPS

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG